food/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='food-main'),
    path('product/<product_id>', views.product, name='product'),
    path('menu/', views.menu, name='food-menu'),
]

foodapp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from registration import views as reg_views
#from menu.views import MenuForm

admin.autodiscover()

urlpatterns = [
    path('', include('food.urls')),
    path('registration/', reg_views.registration, name='register-registration'),
    path('orders/', include('orders.urls'), name='order'),
    path('profile/', reg_views.profile, name='profile'), #if some error here I deleted reg_views.profile
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

class Product(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    description = models.TextField(max_length=250, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    # class Meta:
    #     order_name = "Product"
    #     order_name_plural = "Products"


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products_images/")
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    # class Meta:
    #     order_name = "Photo"
    #     order_name_plural = "Photos"

food/forms.py
from django import forms
from .models import *




food/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from food.models import *


def home(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_iceCream = products_images.filter(product__category__id=3)
    products_images_drinks = products_images.filter(product__category__id=4)

    return render(request, 'food/home.html', locals())

def menu(request):

    return render(request, 'food/menu.html') # {'title': 'Menu'}   {'content': ["If you would like to order by phone or contact us by email, please", "wsiz@students.pl", "+48111111111"]})

def product(request, product_id):
    product = Product.objects.get(id=product_id)


    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request, session_key)


    return render(request, 'food/product.html', locals())

food/templates/food/home.html
{% extends 'base.html' %}

{% block content %}

    <!--<div class="section-top">-->
        <!--<img src="{% static 'food/img/layer_2.png' %}">-->
    <!--</div>-->

    <div class="section section1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        CURRENT SALE
                    </h1>
                </div>
                {% for product_image in products_images %}
                    {% include 'food/product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="section section-shipping hero-bkg-animated">
        <div>
            <h3><b>Free shipping</b></h3>
        </div>
    </div>

    <div class="section section2 ice-cream-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        ICE CREAM
                    </h1>
                </div>
                {% for product_image in products_images_iceCream %}
                    {% include 'food/product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="section section3 drinks-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Drinks
                    </h1>
                </div>
                {% for product_image in products_images_drinks %}
                    {% include 'food/product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>


{% endblock %}

food/templates/food/main.html
{% extends 'base.html' %}
	<link rel="stylesheet" href="% static 'food/main.css' %">

{% block content %}
	<img class="rounded-circle article-img" src="{{ post.author.profile.image.url}}">




{% endblock content %}

food/templates/food/menu.html
{% extends 'base.html' %}

{% block content %}

    <h1>Menu Page</h1>
<br>
<br>
<br>
<br>
    <div  class="container">
        <div class="row">
            <div>
                <from action="" method="POST">{% csrf_token %}
                    {{ form.as_p }}
                <div>
                    <button type="submit" class="btn btn-primary">Send</button>
                </div>
                </from>
            </div>
        </div>
    </div>

{% endblock content %}

food/templates/food/product.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price}} zł
                    </p>
                </div>
                <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                Description
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                                Delivery
                            </a>
                        </li>
                        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
                        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            {{ product.description }}
                        </div>
                        <div role="tabpanel" class="tab-pane" id="delivery">
                            <h3>How we sent a order</h3>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="messages">Contact me by Facebook</div>
                        <div role="tabpanel" class="tab-pane" id="settings">...</div>
                      </div>
                </div>
                <div>
                    <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}">{% csrf_token %}
                        <div class="form-group">
                            <input type="number" class="form-control" name="number" id="number" value="1" min="1" max="50">
                        </div>

                            <div class="form-group">
                                <button type="submit" id="submit-btn" class="btn btn-success btn-buy"
                                    data-product_id = "{{ product.id }}"
                                    data-name = "{{ product.name }}"
                                    data-price = "{{ product.price }}"
                                 >
                                    Buy
                                </button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

food/templates/food/product_item.html
<div class="col-lg-3">
    <div class="product-item">
        <div>
            <a href="{% url 'product' product_image.product.id %}">
                <img src="{{ product_image.image.url }}" class="img-responsive">
            </a>
        </div>

        {% if product_image.product.discount %}
            <div class="discount-container">
                <span>{{ product_image.product.discount }}%</span>
            </div>
        {% endif %}

        <h4>{{ product_image.product.name }}</h4>
        <p>
            {{ product_image.product.description|truncatechars_html:100 }}
        </p>
        <div>
            {{ product_image.product.price }} zł
        </div>
        <div class="add-to-cart-btn">
            <a href="{% url 'product' product_image.product.id %}">
                <button class="btn btn-success">
                    Add to Cart
                </button>
            </a>
        </div>
    </div>
</div>